web:
  build: .
  command: bundle exec rails s -e development -p 3000 -b '0.0.0.0' webrick
  volumes:
    - .:/code
  volumes_from:
    - bundle
  ports:
    - '3000:3000'
  environment:
    - RAILS_ENV=development
    - BUNDLE_APP_CONFIG=/code/.bundle
    - BUNDLE_PATH=/bundle
bundle:
  image: busybox
  volumes:
    - /bundle
