db:
  image: postgres
  ports:
    - '5432'
  environment:
    - POSTGRES_PASSWORD=docker_pass
bundle:
  image: busybox
  volumes:
    - /bundle
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/code
  volumes_from:
    - bundle
  ports:
    - '3000:3000'
  links:
    - db
  environment:
    - RAILS_ENV=development
